[package]
name = "deears-ex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deears = { path = "./engine" }
lewton = "0.10.2"
cpal = "0.15.2"
rand = "0.8.5"
#alto = "3.0.4"
